name: Build and Release Resume

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install LaTeX packages
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            texlive-latex-recommended \
            texlive-latex-extra \
            texlive-fonts-recommended \
            texlive-fonts-extra \
            latexmk

      - name: Compile main.tex
        run: |
          latexmk -pdf -interaction=nonstopmode main.tex
          mv main.pdf resume.pdf

      - name: Create GitHub Release with resume.pdf
        uses: ncipollo/release-action@v1
        with:
          tag: v1.0.${{ github.run_number }}
          name: Resume Release v1.0.${{ github.run_number }}
          artifacts: resume.pdf
          draft: false
          prerelease: false
          allowUpdates: true
          body: "Compiled resume from main.tex."
          generateReleaseNotes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: Configure rclone
        run: |
          mkdir -p ~/.config/rclone
          echo -e "${{ secrets.RCLONE_CONFIG }}" > ~/.config/rclone/rclone.conf

      - name: Upload resume.pdf to OneDrive
        run: |
          rclone copy resume.pdf onedrive:Public/ --progress
